---

- name: Download Prometheus server
  unarchive:
    src={{ url_prom }}
    dest=/usr/local/bin
    copy=no

- name: create synbolic link for prometheus server
  file: src=/usr/local/bin/{{ name_prom }}/prometheus dest=/usr/local/bin/prometheus state=link

- name: create /usr/local/bin/prometheus/prometheus.yml
  template: src=templates/prometheus.yml dest=/usr/local/bin/{{ name_prom }} mode=0755 backup=yes

- name: create prometheus.service
  template: src=templates/prometheus.service dest=/etc/systemd/system/

- name: create prometheus.service option file
  template: src=templates/env dest=/usr/local/bin/{{ name_prom }} mode=0755

- name: create prometheus.rules
  template: src=templates/prometheus.rules dest=/usr/local/bin/{{ name_prom }} mode=0755

- name: enable prometheus.service and start
  systemd:
    name: prometheus.service
    state: restarted
    enabled: True

- name: install grafana rpm from a remote repo
  yum:
    name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.5.2-1.x86_64.rpm
    state: present

- name: enable grafana-server
  systemd:
    name: grafana-server
    daemon-reload: yes
    state: started
    enabled: True