---

- name: Download Prometheus server
  unarchive:
    src={{ url_prom }}
    dest=/tmp
    copy=no

- name: copy prometheus-server
  copy:
    src: /tmp/{{ name_prom }}/
    dest: /usr/local/prometheus
    force: no

- name: chmod bin
  file:
   path: /usr/local/prometheus/prometheus
   mode: 0755

- name: chmod bin
  file:
   path: /usr/local/prometheus/promtool
   mode: 0755

- name: create synbolic link for prometheus server
  file: src=/usr/local/prometheus/prometheus dest=/usr/local/bin/prometheus/ state=link

- name: create /usr/local/prometheus/prometheus.yml
  template: src=templates/prometheus.yml dest=/usr/local/prometheus/ mode=0755

- name: create prometheus.service
  template: src=templates/prometheus.service dest=/etc/systemd/system/

- name: create file_sd
  template: src=templates/file_sd.yml dest=/usr/local/prometheus/

- name: create prometheus.service option file
  template: src=templates/env dest=/usr/local/prometheus/ mode=0755

- name: create prometheus.rules
  template: src=templates/prometheus.rules dest=/usr/local/prometheus/ mode=0755

- name: enable prometheus.service and start
  systemd:
    name: prometheus.service
    state: restarted
    enabled: True

- name: install grafana rpm from a remote repo
  yum:
    name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.5.2-1.x86_64.rpm
    state: present

- name: enable grafana-server
  systemd:
    name: grafana-server
    daemon-reload: yes
    state: started
    enabled: True
