---

- name: Download node_exporter
  unarchive:
    src={{ url_node }}
    dest=/usr/local/
    copy=no

- name: rename node_exporter directory
  copy:
    src: /usr/local/{{ name_node }}/
    dest: /usr/local/node_exporter
    force: no

- name: remove unarchived file
  file:
    path: /usr/local/{{ name_node }}
    state: absent

- name: chmod node_exporter
  file:
   path: /usr/local/node_exporter/node_exporter
   mode: 0755

- name: create synbolic link
  file: src=/usr/local/node_exporter/node_exporter dest=/usr/local/bin/node_exporter state=link

- name: create node_exporter.service
  template: src=templates/node_exporter.service dest=/etc/systemd/system/

- name: create node_exporter.service option file
  template: src=templates/env dest=/usr/local/node_exporter mode=0755

- name: enable node_exporter.service and start
  systemd:
    name: node_exporter.service
    state: started
    enabled: True
