---

- name: Download {{ name_alert }}
  unarchive:
    src={{ url_alert }}
    dest=/tmp/
    copy=no

- name: copy {{ name_alert }}
  copy:
    src: /tmp/{{ name_alert }}/
    dest: /usr/local/alertmanager
    force: no

- name: chmod bin
  file:
   path: /usr/local/alertmanager/alertmanager
   mode: 0755

- name: chmod bin
  file:
   path: /usr/local/alertmanager/amtool
   mode: 0755
- name: create config
  template: src=templates/alertmanager.yml dest=/usr/local/alertmanager mode=0755

- name: create alertmanager.service
  template: src=templates/alertmanager.service dest=/etc/systemd/system/

- name: create alertmanager.service option file
  template: src=templates/env dest=/usr/local/alertmanager mode=0755


- name: enable alertmanager.service and start
  systemd:
    name: alertmanager.service
    state: restarted
    enabled: True
