global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  # All alerts in a notification have the same value for these labels.
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prometheus'
    text: "<https://prometheus.io/|link test>"
