global:
  slack_api_url: <webhook url>

route:
  receiver: 'slack-notifications'
  # All alerts in a notification have the same value for these labels.
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#prometheus'
    text: "<https://prometheus.io/|link test>"
